name: Set environment variables from configuration file
description: Reads in the a configuration file and outputs the contents to environmental variables.
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  config_file:
    description: The path to the configuration file. Defaults to env.yaml in the .github folder.
    required: false
    default: ".github/env.yaml"
